# Generated by Django 3.1.2 on 2021-05-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_interviewer_user',
            new_name='first_interviewer',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='hr_interviewer_user',
            new_name='hr_interviewer',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='second_interviewer_user',
            new_name='second_interviewer',
        ),
    ]
