# Generated by Django 3.1.2 on 2021-05-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210505_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_interviewer',
            new_name='first_interviewer_user',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='hr_interviewer',
            new_name='hr_interviewer_user',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='second_interviewer',
            new_name='second_interviewer_user',
        ),
    ]
