# Generated by Django 3.1.3 on 2021-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.AutoField(primary_key=True, serialize=False)),
                ('countryid', models.PositiveIntegerField()),
                ('chn_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.PositiveIntegerField(blank=True, null=True)),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('chn_name', models.CharField(max_length=64)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('country_logo', models.CharField(blank=True, max_length=120, null=True)),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceid', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.IntegerField(blank=True, null=True)),
                ('chn_name', models.CharField(blank=True, max_length=64, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
    ]
